services:
  postgres:
    image: postgres:18-alpine3.23
    container_name: khammerson_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - khammerson_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: khammerson_server
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:4000"
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # Монтируем только исходники для hot-reload
      - ./apps/server/src:/app/apps/server/src
      - ./apps/server/test:/app/apps/server/test
      # Защищаем node_modules от перезаписи
      - /app/node_modules
      - /app/apps/server/node_modules
    working_dir: /app/apps/server
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - khammerson_network
    command: nest start --watch

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: khammerson_web
    restart: unless-stopped
    ports:
      - "${WEB_PORT}:3006"
    environment:
      NODE_ENV: development
    volumes:
      # Монтируем исходники для hot-reload
      - ./apps/web/src:/app/apps/web/src
      - ./apps/web/index.html:/app/apps/web/index.html
      - ./apps/web/vite.config.ts:/app/apps/web/vite.config.ts
      # Защищаем node_modules
      - /app/node_modules
      - /app/apps/web/node_modules
    working_dir: /app/apps/web
    depends_on:
      - server
    networks:
      - khammerson_network
    command: pnpm run dev

volumes:
  postgres_data:

networks:
  khammerson_network:
    driver: bridge